### ISSUE TITLE
Use html comment to mark comment for upsert

### ISSUE THREAD

**Issue by annervisser** [ScientaNL/lokalise-tms-github-action#18]
By putting an `<!-- html comment -->` in the pull request comment it is easier to identify which comment to upsert. This would remove the need to check for summary text and user

If possible, a custom tag input could be added, to differentiate multiple instances of the same action (if that has any application). Inspiration from https://github.com/thollander/actions-comment-pull-request

Default:
```
<!-- ScientaNL/lokalise-tms-github-action "default" -->
```

With custom tag:
```
<!-- ScientaNL/lokalise-tms-github-action "my_custom_tag" -->
```

Relevant code:
https://github.com/ScientaNL/lokalise-tms-github-action/blob/9e03dafcf21428b475b6b1ded57fef33ae5b19fe/src/lib/github-pr/github-comment-using-github.ts#L31

**Comment by HarmenM** [comment]
Nice suggestion 👍
